package tech.pegasys.teku.bls.impl.blst.swig;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Pairing {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Pairing(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Pairing obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blstJNI.delete_Pairing(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Pairing(boolean hash_or_encode, byte[] DST) {
    this(blstJNI.new_Pairing__SWIG_0(hash_or_encode, DST), true);
  }

  public Pairing(boolean hash_or_encode, String DST) {
    this(blstJNI.new_Pairing__SWIG_1(hash_or_encode, DST), true);
  }

  public BLST_ERROR aggregate(P1_Affine pk, P2_Affine sig, byte[] msg, byte[] aug) {
    return BLST_ERROR.swigToEnum(blstJNI.Pairing_aggregate__SWIG_0(swigCPtr, this, P1_Affine.getCPtr(pk), pk, P2_Affine.getCPtr(sig), sig, msg, aug));
  }

  public BLST_ERROR aggregate(P1_Affine pk, P2_Affine sig, byte[] msg) {
    return BLST_ERROR.swigToEnum(blstJNI.Pairing_aggregate__SWIG_2(swigCPtr, this, P1_Affine.getCPtr(pk), pk, P2_Affine.getCPtr(sig), sig, msg));
  }

  public BLST_ERROR aggregate(P2_Affine pk, P1_Affine sig, byte[] msg, byte[] aug) {
    return BLST_ERROR.swigToEnum(blstJNI.Pairing_aggregate__SWIG_3(swigCPtr, this, P2_Affine.getCPtr(pk), pk, P1_Affine.getCPtr(sig), sig, msg, aug));
  }

  public BLST_ERROR aggregate(P2_Affine pk, P1_Affine sig, byte[] msg) {
    return BLST_ERROR.swigToEnum(blstJNI.Pairing_aggregate__SWIG_5(swigCPtr, this, P2_Affine.getCPtr(pk), pk, P1_Affine.getCPtr(sig), sig, msg));
  }

  public BLST_ERROR mul_n_aggregate(P1_Affine pk, P2_Affine sig, java.math.BigInteger scalar, byte[] msg, byte[] aug) {
    return BLST_ERROR.swigToEnum(blstJNI.Pairing_mul_n_aggregate__SWIG_0(swigCPtr, this, P1_Affine.getCPtr(pk), pk, P2_Affine.getCPtr(sig), sig, scalar.toByteArray(), msg, aug));
  }

  public BLST_ERROR mul_n_aggregate(P1_Affine pk, P2_Affine sig, java.math.BigInteger scalar, byte[] msg) {
    return BLST_ERROR.swigToEnum(blstJNI.Pairing_mul_n_aggregate__SWIG_2(swigCPtr, this, P1_Affine.getCPtr(pk), pk, P2_Affine.getCPtr(sig), sig, scalar.toByteArray(), msg));
  }

  public BLST_ERROR mul_n_aggregate(P2_Affine pk, P1_Affine sig, java.math.BigInteger scalar, byte[] msg, byte[] aug) {
    return BLST_ERROR.swigToEnum(blstJNI.Pairing_mul_n_aggregate__SWIG_3(swigCPtr, this, P2_Affine.getCPtr(pk), pk, P1_Affine.getCPtr(sig), sig, scalar.toByteArray(), msg, aug));
  }

  public BLST_ERROR mul_n_aggregate(P2_Affine pk, P1_Affine sig, java.math.BigInteger scalar, byte[] msg) {
    return BLST_ERROR.swigToEnum(blstJNI.Pairing_mul_n_aggregate__SWIG_5(swigCPtr, this, P2_Affine.getCPtr(pk), pk, P1_Affine.getCPtr(sig), sig, scalar.toByteArray(), msg));
  }

  public void commit() {
    blstJNI.Pairing_commit(swigCPtr, this);
  }

  public BLST_ERROR merge(Pairing ctx) {
    return BLST_ERROR.swigToEnum(blstJNI.Pairing_merge(swigCPtr, this, Pairing.getCPtr(ctx), ctx));
  }

  public boolean finalverify(PT sig) {
    return blstJNI.Pairing_finalverify__SWIG_0(swigCPtr, this, PT.getCPtr(sig), sig);
  }

  public boolean finalverify() {
    return blstJNI.Pairing_finalverify__SWIG_1(swigCPtr, this);
  }

}
