package tech.pegasys.teku.bls.impl.blst.swig;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SecretKey {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SecretKey(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SecretKey obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        blstJNI.delete_SecretKey(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void keygen(byte[] IKM, String info) {
    blstJNI.SecretKey_keygen__SWIG_0(swigCPtr, this, IKM, info);
  }

  public void keygen(byte[] IKM) {
    blstJNI.SecretKey_keygen__SWIG_1(swigCPtr, this, IKM);
  }

  public void from_bendian(byte[] in) {
    blstJNI.SecretKey_from_bendian(swigCPtr, this, in);
  }

  public void from_lendian(byte[] in) {
    blstJNI.SecretKey_from_lendian(swigCPtr, this, in);
  }

  public byte[] to_bendian() { return blstJNI.SecretKey_to_bendian(swigCPtr, this); }

  public byte[] to_lendian() { return blstJNI.SecretKey_to_lendian(swigCPtr, this); }

  public SecretKey() {
    this(blstJNI.new_SecretKey(), true);
  }

}
